FROM node:21.6.2

# Next.js app lives here
WORKDIR /app

COPY package*.json

# Set production environment
ENV NODE_ENV="production"

# Copy application code
COPY . .

# Install dependencies
RUN npm install

RUN npm run build

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD [ "npm", "run", "start" ]