
FROM node:21.6.2-slim as base

# Next.js app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV="dev"

# Copy application code
COPY . .

# Install dependencies
RUN npm install

# Final stage for app image
FROM base

# Copy built application
COPY --from=base /app /app

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD [ "npm", "run", "start" ]