name: Docker를 사용하여 Next.js 빌드 및 배포

on:
  push:
    branches:
      - main

  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

        name: Docker Build and Push
        runs-on: ubuntu-latest
        concurrency: deploy-group # optional: ensure only one action runs at a time
        steps:
          - name: Login to DockerHub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v2
            with:
              push: true
              tags: jsh5890/manaj-fe:latest
              context: .
              file: ./DockerfileHub
