name: Fly Deploy
on:
  push:
    branches:
      - main    # change to main if needed
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - name: 👀 Read app name
        uses: SebRollen/toml-action@v1.0.2
        id: app_name
        with:
          file: fly.toml
          field: app
      - name: 🚀 Deploy Production
        uses: superfly/flyctl-actions/@1.5
        with:
          args: deploy --remote-only --build-arg NEXT_PUBLIC_KAKAO_OAUTH_URL=${{ secrets.OAUTH_URL }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
